services:
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: prospectSync
      POSTGRES_USER: User
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - psql_volume_bp:/var/lib/postgresql/data

volumes:
  psql_volume_bp:
